# Generated by Django 4.0.1 on 2022-01-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='heardEvent',
        ),
    ]
