# Generated by Django 4.0.1 on 2022-01-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heard', '0002_rename_event_heardevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heardevent',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='heardevent',
            name='location_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
